FROM python:3.5-alpine
MAINTAINER Kelvin Li <kelvin.li@memodir.com>

EXPOSE 9000

ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH=/code/src:/code/ \
    DJANGO_SETTINGS_MODULE=django_project.settings \
    LIBRARY_PATH=/lib:/usr/lib \
    INSTALL_PATH=/code

RUN mkdir $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY . $INSTALL_PATH/

RUN apk update && \
    apk add postgresql-libs bash \
        # Pillow dependencies
        jpeg-dev zlib-dev && \
    apk add --virtual .build-deps gcc musl-dev postgresql-dev && \
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps

ENTRYPOINT ["/code/.docker/app/docker-entrypoint.sh"]