# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('download_link', models.CharField(max_length=255, verbose_name='Download Link')),
                ('live_link', models.CharField(max_length=255, verbose_name='Live Link')),
                ('github', models.CharField(max_length=255, verbose_name='Github')),
                ('description', models.TextField(blank=True, verbose_name='Summary')),
                ('cover_image', models.ImageField(blank=True, help_text='A 300x300 image for the project', null=True, upload_to='users/%Y/%m', verbose_name='Project Image')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is this experience public ?')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, max_length=255, verbose_name='LinkedIn')),
                ('wechat', models.CharField(blank=True, max_length=255, verbose_name='Wechat')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='Facebook')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='Github')),
                ('personal_site', models.CharField(blank=True, max_length=255, verbose_name='Personal Site')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is this experience public?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], db_index=True, max_length=5)),
                ('position', models.CharField(max_length=255, verbose_name='Job Position')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('date_start', models.DateTimeField(verbose_name='Start Date')),
                ('date_end', models.DateTimeField(verbose_name='End Date')),
                ('contribution', models.TextField(blank=True, verbose_name='Your highlight contribution')),
                ('keywords', models.TextField(blank=True, default='', help_text='The words that might search for when looking ', verbose_name='Keywords')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='resume.WorkExperience')),
            ],
            options={
                'ordering': ('language',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.UserProfile'),
        ),
    ]
