# Generated by Django 2.0.7 on 2018-07-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('download_link', models.CharField(max_length=255, verbose_name='Download Link')),
                ('live_link', models.CharField(max_length=255, verbose_name='Live Link')),
                ('github', models.CharField(max_length=255, verbose_name='Github')),
                ('description', models.TextField(blank=True, verbose_name='Summary')),
                ('cover_image', models.ImageField(blank=True, help_text='A 300x300 image for the project', null=True, upload_to='projects/%Y/%m', verbose_name='Project Image')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is this project public?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is this experience public?')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('', '*--- select language ---'), ('en', 'English'), ('zh-hans', 'Chinese')], db_index=True, max_length=30, verbose_name='Language')),
                ('position', models.CharField(max_length=255, verbose_name='Job position')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('contribution', tinymce.models.HTMLField(blank=True, default='', verbose_name='Highlighted contribution')),
                ('keywords', models.TextField(blank=True, default='', help_text='The words that might search for when looking', verbose_name='Keywords')),
                ('related_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='resume.WorkExperience')),
            ],
            options={
                'ordering': ('language',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='workexperiencetranslation',
            unique_together={('related_model', 'language')},
        ),
    ]
