# Generated by Django 2.0.3 on 2018-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180327_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_upload_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Keep the original upload file name'),
        ),
    ]
