# Generated by Django 2.0.3 on 2018-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_userprofile_photo_upload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_upload_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Original photo name'),
        ),
    ]
