# Generated by Django 2.0.4 on 2018-06-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20180614_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workexperiencetranslation',
            unique_together={('related_model', 'language')},
        ),
    ]
