# Generated by Django 2.0.4 on 2018-06-15 05:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20180614_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='contribution',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Highlighted contribution'),
        ),
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='date_start',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Job position'),
        ),
    ]
