# Generated by Django 2.0.4 on 2018-06-21 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20180615_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiencetranslation',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='workexperiencetranslation',
            name='date_start',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is this project public?'),
        ),
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='language',
            field=models.CharField(choices=[('', '*--- select language ---'), ('en', 'English'), ('zh-hans', 'Chinese')], db_index=True, max_length=30, verbose_name='Language'),
        ),
    ]
